name: synergy
favicon: null
layout_spectrum: 0.1787
typography_spectrum: 0.3375648797955364
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#910000'
    - '#000000'
    - '#550000'
    - '#ff0000'
    - '#aa0000'
  brandStrength: 1
  lightness: 0.628493293421343
  saturation: 0.2930008755065501
  rhythmicContrast: 0.15085171326063573
purpose: []
